"""This file is titled supportfunc.py, with class naming convention, 
with the purpose of being used to add support functions for homework
assignments.

"""

# Imports

import os # standard library imports first
import numpy as np
# import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
# import astropy.io.fits as fits

# My functions
# Creating a square function

def square(x):
    """A function that takes an input of a scalar
    or an array if any dimension or type and returns
    the square.

    Parameters
    -----------
    x: int or array_like

    Returns
    -------
    squared result: int or array

    References
    ----------
    https://numpy.org/doc/2.2/reference/generated/numpy.asarray.html

    Examples
    --------

    For an integer

    >>> x = 9
    >>> print(square(x))
    81

    For an array

    >>> a=[1,2,3]
    >>> print(square(a))
    [1, 4, 9]

    """

    x = np.asarray(x) # Converts input to array
    return x**2

def squareplot(low, high, n, saveplot=False):
    """A function that creates 2 sets of evenly
    spaced numbers and saves according to user
    filename preference.

    Parameters
    -----------
    low: int
    high: int
    n: int
    saveplot: str
    filename as a string, default is no save

    Returns
    -------
    plot: of x axis generated by low, high, and n
    and y axis of squared x

    Examples
    --------

    I want to plot on an x axis of 10 evenly spaced numbers
    and name the file squareplot.pdf

    >>> a = 0
    >>> b = 10
    >>> n = 11
    >>> name = "squareplot"
    >>> squareplot(a, b, n, name)
    plot shown

    """

    x = np.linspace(low, high, n)
    y = square(x)

    plt.figure()
    plt.plot(x, y)
    plt.title("Square Function")
    plt.xlabel("Input")
    plt.ylabel("Output")

    if saveplot:
        plt.savefig(f"{saveplot}.pdf", format="pdf")
        plt.show()
        print("Plot saved as .pdf.")
    else:
        plt.show()
        print("Plot displayed but not saved, input string in 4th arguement to save.")

    pass
